## Aula - 08/05/2025

In [1]:
import math # importação total

from math import cos, sin # importação parcial

In [3]:
math.cos(10)

-0.8390715290764524

In [4]:
from numpy import cos

In [ ]:
cos(10) 

np.float64(-0.8390715290764524)

Vale o último pacote importado (no caso de repetição)

In [7]:
import numpy as np
np.cos(10)

np.float64(-0.8390715290764524)

In [8]:
import matplotlib as plt

In [10]:
dados = np.array([11, 3, 66, 77, 33])
print(dados)
type(dados)

[11  3 66 77 33]


numpy.ndarray

In [12]:
print(len(dados))
print(dados.size)
print(dados.shape)
print(dados.dtype)

5
5
(5,)
int64


In [18]:
matriz = np.array([[1, 2, 3], [3, 2, 1]])
print(matriz)
print(len(matriz))
print(matriz.size)
print(matriz.shape)
print(matriz.dtype)

[[1 2 3]
 [3 2 1]]
2
6
(2, 3)
int64


In [ ]:
dados_e = np.empty(7) # Outra forma de criar vetores
print(dados_e)

[-6.95250701e-310  7.39122206e-321  0.00000000e+000  9.62938509e-312
  0.00000000e+000  3.25060610e-319  0.00000000e+000]


In [24]:
dados_f = np.empty(7)
dados_f.fill(3.45)
print(dados_f)

[3.45 3.45 3.45 3.45 3.45 3.45 3.45]


In [27]:
dados_a = np.arange(0, 7, 2)
print(dados_a)
dados_afloar = np.arange(7.0)
print(dados_a)

[0 2 4 6]
[0 2 4 6]


In [37]:
dados_ones = np.ones(7)
dados_onesdim = np.ones([3, 5])
print(dados_ones)
print(dados_onesdim)

# mesmo efeito - qual seria mais eficiente?
vetor_A = np.empty(10)
vetor_A = np.ones(10)
print(f"Teste de eficiência: ", vetor_A)
%time vetor_A = np.ones(10)
%time vetor_A = np.empty(10)

[1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Teste de eficiência:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
CPU times: total: 0 ns
Wall time: 81.3 μs
CPU times: total: 0 ns
Wall time: 34.3 μs


In [39]:
dados_zero = np.zeros((3, 5))
print(dados_zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [41]:
dados_rd = np.random.rand(7)
print(dados_rd)

[0.45000836 0.95367174 0.88165556 0.10521803 0.35424602 0.28964532
 0.4414655 ]
