In [ ]:
#
# NumPy
# Prof. Douglas Machado Tavares
#

In [ ]:
# O NumPy, abreviatura de Numerical Python (Python Numérico)  é um 
# pacote (um conjunto de bibliotecas) de código aberto que fornece
# inúmeras soluções numéricas  e estruturas de dados (como vetores
# e matrizes) eficientes e de alta capacidade de armazenamento.

In [2]:
# Importando o pacote NumPy :-D

import numpy as np

In [ ]:
#
# Array:
#        Operações
#

In [ ]:
# Array com um número:

In [3]:
dados_a = np.random.randint(100, 900, 8)
print(dados_a)

[661 371 206 804 274 341 667 427]


In [4]:
dados_b = dados_a + 100_000
print(dados_b)

[100661 100371 100206 100804 100274 100341 100667 100427]


In [5]:
dados_b = dados_a * 10
print(dados_b)

[6610 3710 2060 8040 2740 3410 6670 4270]


In [ ]:
print(dados_a)
dados_b = dados_a / 100
print(dados_b)

In [6]:
dados_x = np.array([11, 22, 33, 44, 55])
print(dados_x)
dados_x += 1
print(dados_x)

[11 22 33 44 55]
[12 23 34 45 56]


In [ ]:
# Array com array:

In [7]:
dados_x = np.array([50, 30, 40, 2, 10])
dados_y = np.array((2, 3, 4, 5, 6))

In [8]:
dados_r = dados_x + dados_y
print(dados_r) # Soma elemento a elemento

[52 33 44  7 16]


In [9]:
dados_r = dados_x * dados_y
print(dados_r) # Multiplicação elemento por elemento

[100  90 160  10  60]


In [10]:
dados_r = dados_x - dados_y
print(dados_r) # Subtração elemento a elemento

[48 27 36 -3  4]


In [11]:
dados_r = dados_x / dados_y
print(dados_r)

[25.         10.         10.          0.4         1.66666667]


In [12]:
dados_r = dados_x ** dados_y
print(dados_r)

[   2500   27000 2560000      32 1000000]


In [13]:
dados_x > dados_y # Vetor contendo booleanos, comparação elemento a elemento

array([ True,  True,  True, False,  True])

In [14]:
dados_x < dados_y

array([False, False, False,  True, False])

In [15]:
dados_r = dados_x > dados_y
print(dados_r)
print(dados_r.any())
# dados_r.any() -> Existe no mínimo um True (algum de x é maior que algum de y)?

[ True  True  True False  True]
True


In [16]:
dados_r = dados_x > dados_y
print(dados_r)
print(dados_r.all())
# dados_r.all() -> Todos são True (todos de x são maiores que todos de y)?

[ True  True  True False  True]
False


In [ ]:
# Operação de Vetores no R³ e no R²:

In [17]:
vet_x = np.array([1, 2, 3])
vet_y = np.array([4, 5, 6])

In [18]:
# Produto de um escalar por vetor:
vet_r = 10 * vet_x
print(vet_r)

[10 20 30]


In [19]:
# Produto Escalar entre vetores:
p = vet_x.dot(vet_y)
print(p)
# Obs.: Produto escalar é o mesmo que: sum(vet_x * vet_y)

32


In [20]:
# Produto Vetorial:
vet_r = np.cross(vet_x, vet_y)
print(vet_r)

[-3  6 -3]


In [ ]:
#
# Array:
#        Algumas Funções
#

In [ ]:
# Funções da biblioteca math.
# 
# A maioria das funções da biblioteca  math foram 
# reimplementadas na  NumPy de forma a aceitarem
# como parâmetro um float ou um array.

### OffTopic: 
Utilizar os métodos do numpy é o mesmo que utilizar os métodos da math já que numpy implementa/sobrecreve a math. 
Portanto é mais eficiente importar apenas o numpy.

In [21]:
dados_x = np.array([5, 3, np.pi/2, np.e])
print(dados_x)
dados_r = np.sin(dados_x)
print(dados_r)

[5.         3.         1.57079633 2.71828183]
[-0.95892427  0.14112001  1.          0.41078129]


In [22]:
print(np.sin(20))

0.9129452507276277


In [23]:
print(dados_x)
dados_r = np.cos(dados_x)
print(dados_r)

[5.         3.         1.57079633 2.71828183]
[ 2.83662185e-01 -9.89992497e-01  6.12323400e-17 -9.11733915e-01]


In [24]:
dados_x = np.array((1000, 100, 10, 3, 2))
print(dados_x)
dados_r = np.log10(dados_x)
print(dados_r)

[1000  100   10    3    2]
[3.         2.         1.         0.47712125 0.30103   ]


In [25]:
dados_x = np.array((1024, 1000, np.e))
print(dados_x)
dados_r = np.log(dados_x)
print(dados_r)
# Obs.: Logaritmo natural.

[1024.         1000.            2.71828183]
[6.93147181 6.90775528 1.        ]


In [ ]:
# Fim ;-)