In [3]:
#
# NumPy
# Prof. Douglas Machado Tavares
#

In [4]:
# O NumPy, abreviatura de Numerical Python (Python Numérico)  é um 
# pacote (um conjunto de bibliotecas) de código aberto que fornece
# inúmeras soluções numéricas  e estruturas de dados (como vetores
# e matrizes) eficientes e de alta capacidade de armazenamento.

In [5]:
# Criado em 2005 por Travis Oliphant,  o projeto NumPy foi baseado
# nos projetos  Numeric  e  Numarray  com o  objetivo  de reunir a 
# comunidade  em  torno  de um único  pacote  de  processamento de 
# arrays (vetores e matrizes).
#
# NumPy é considerado um dos pacotes básicos mais importantes para
# o processamento numérico em Python.

In [2]:
# Importando o pacote NumPy :-D

import numpy as np

In [7]:
#
# Array:
#        Criação
#

In [ ]:
dados_x = np.array([11, 3, 66, 77, 33, 55, 77])
print(dados_x) # Não separa os elementos com vírgulas

[11  3 66 77 33 55 77]


In [4]:
type(dados_x)

numpy.ndarray

In [ ]:
print(len(dados_x)) # Retorna o comprimento do objeto (off topic: chama um método dentro da estrutura)
print(dados_x.size) # Retorna o comprimento do objeto (dúvida: diferença entre size e len - linguagem altamente ortogonal)
print(dados_x.shape) # Retorna a quantidade de elementos por dimensão
print(dados_x.dtype) # Retorna o tipo dos dados armazenados no ndarray

7
7
(7,)
int64


In [ ]:
dados_m = np.array([[15, 17], [31, 37], [57, 59]]) # Listas de listas/Tuplas de tuplas de MESMO TAMANHO
print(dados_m)

[[15 17]
 [31 37]
 [57 59]]


In [9]:
print(len(dados_m)) # Comprimento raso
print(dados_m.size) # Comprimento profundo - quantidade de objetos armazenados
print(dados_m.shape)
print(dados_m.dtype)

3
6
(3, 2)
int64


In [ ]:
# Transposta:
dados_tm = dados_m.T 
print(dados_tm)

[[15 31 57]
 [17 37 59]]


In [12]:
dados_e = np.empty(7) # Insere os bits que estavam armazenados na memória que foi alocada na criação do array
print(dados_e)

[1.33511290e-306 1.11260619e-306 1.37961370e-306 1.33511561e-306
 1.11261027e-306 3.59412797e-317 0.00000000e+000]


In [ ]:
dados_e.fill(3.1415) # Preenche o array ja existente com 3.1415
print(dados_e)

[3.1415 3.1415 3.1415 3.1415 3.1415 3.1415 3.1415]


In [ ]:
dados_m = np.empty((3, 4)) # A tupla representa a dimensão com os bits que estavam armazenados na memória que foi alocada na criação do array
print(dados_m)

[[9.94533826e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.69119330e-306 1.45141481e-047 7.62490703e+169 5.40778085e-066]
 [4.51664331e-037 1.73793727e-047 5.88571711e-062 3.50383775e-033]]


In [20]:
dados_x = np.arange(7) # [0, 7)   Cria um vetor contendo os numeros inteiros de 0 a 6
print(dados_x)

[0 1 2 3 4 5 6]


In [21]:
dados_x = np.arange(100, 182, 5)  # [100, 182)
print(dados_x)

[100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180]


In [22]:
dados_x = np.arange(7.0) # [0, 7.0) 
print(dados_x)

[0. 1. 2. 3. 4. 5. 6.]


### *Parei de anotar aqui*

In [23]:
dados_u = np.ones(7)
print(dados_u)

[1. 1. 1. 1. 1. 1. 1.]


In [24]:
dados_u = np.ones((3, 5))
print(dados_u)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
dados_z = np.zeros(7)
print(dados_z)

[0. 0. 0. 0. 0. 0. 0.]


In [24]:
dados_z = np.zeros((3, 5))
print(dados_z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Ao trabalhar com geração  de números pseudoaleatórios, você
# pode configurar a semente  de geração. Assim, será possível
# repetir futuramente uma sequência que já foi gerada.
# >>> np.random.seed(7070)
#
#
# Toda vez que uma Máquina Virtual Python é iniciada uma nova
# semente é configurada. Assim, não é necessário fazer:
# >>> np.random.seed(time.time_ns())

In [25]:
# Array com 7 números floats aleatórios entre 0 e 1.
dados_rd = np.random.rand(7)
print(dados_rd)

[0.61799568 0.60629716 0.95525689 0.40270982 0.35370934 0.22782649
 0.70403681]


In [26]:
dados_rd = np.random.rand(3, 5)
print(dados_rd)
# Obs.: Diferente de np.ones e np.zeros a função np.random.rand não recebe uma tupla :-(

[[0.81178219 0.60124399 0.19453442 0.51872831 0.92604759]
 [0.88029699 0.4674699  0.83002514 0.81239922 0.81681226]
 [0.23977488 0.38829448 0.6115422  0.43370725 0.21347466]]


In [27]:
# Array com 7 números inteiros aleatórios entre 20 e 30. 
dados_rd = np.random.randint(20, 30, 7)
print(dados_rd)

[27 24 24 29 20 20 24]


In [28]:
dados_rd = np.random.randint(20, 30, (3, 5))
print(dados_rd)

[[23 28 23 27 27]
 [20 24 27 29 21]
 [29 23 21 24 25]]


In [29]:
# Array contendo  15 alturas geradas de forma  aleatória
# seguindo uma Distribuição Normal de mu=169 e sigma=17.

dados_alturas = np.random.normal(169, 17, 15)
print(dados_alturas)

[153.28592981 180.66523711 192.00201717 171.3866205  189.02889122
 179.75907144 125.90893591 165.00439374 179.68894888 200.09466975
 174.61686555 165.51659597 197.91171866 147.31768499 142.58255736]


In [ ]:
# Array de  duas dimensões  contento  15  alturas geradas de forma 
# aleatória seguindo uma Distribuição Normal de mu=169 e sigma=17.

dados_alturas = np.random.normal(169, 17, (3, 5))
print(dados_alturas)

In [ ]:
# Array contendo 10 números (floats) igualmente espaçados
# onde o primeiro número é 100 e o último é 150.
dados_v = np.linspace(100, 150, 15)
print(dados_v)

In [ ]:
#
# Array:
#        Tipo dos Elementos Armazenados
#

In [ ]:
dados_a = np.array([11, 3, 66, 77, 33, 55, 77])
print(dados_a)
print(dados_a.dtype)

In [ ]:
dados_a = np.array([11, 3, 66, 77, 33, 55, 77], dtype='int64')
print(dados_a)
print(dados_a.dtype)

In [ ]:
dados_b = np.array([11, 3, 66, 77, 33, 55, 77], dtype='int32')
print(dados_b)
print(dados_b.dtype)

In [ ]:
dados_c = np.array([11, 3, 66, 77, 33, 55, 77], dtype='int16')
print(dados_c)
print(dados_c.dtype)

In [ ]:
dados_d = np.array([11, 3, 66, 77, 33, 55, 77], dtype='float32')
print(dados_d)
print(dados_d.dtype)

In [ ]:
dados_e = np.array([11, 3, 66, 77, 33, 55, 77], dtype='float64')
print(dados_e)
print(dados_e.dtype)

In [ ]:
dados_f = np.array([11, 3, 66, 77, 33, 55, 77], dtype='float128')
print(dados_f)
print(dados_f.dtype)

In [ ]:
dados_cx = np.array([11, 3, 66, 77, 33, 55, 77], dtype='complex')
print(dados_cx)
print(dados_cx.dtype)

In [ ]:
dados_cx = np.array([complex(11, 3), 66, 77, complex(3.3, 55), 3.1415])
print(dados_cx)
print(dados_cx.dtype)

In [ ]:
# Lembre-se. Arrays são homogêneos. Se uma lista heterogênea for passada
# como parâmetro para o construtor do array, tipos serão convertidos.
dados_g = np.array([11, 3, 6.6, 77, 33, 55, 77])
print(dados_g)
print(dados_g.dtype)
# Obs.: O único float 6.6 fez com que todos os demais elementos 
#       fossem armazenados como float.

In [ ]:
dados_s = np.array([11, 3, 6.6, 'CEFET-MG', 77, 33, 55])
print(dados_s)
print(dados_s.dtype)
# Obs.: A única string 'CEFET-MG' fez com que todos os demais
#       elementos fossem armazenados como strings de tamanho 32.

In [ ]:
dados_uf = np.array(['AC', 'AL', 'BA', 'ES', 'MG', 'SP', 'RN'])
print(dados_uf)
print(dados_uf.dtype)

In [ ]:
dados_t = np.array(['A1', 'A2', 'PP3', 'Q1', 'Q2'])
print(dados_t)
print(dados_t.dtype)

In [ ]:
dados_x = np.array([18, 36, 73, 5, 77], dtype='int32')
print(dados_x)
print(dados_x.dtype)

dados_x[2] = 123.77
print(dados_x)
print(dados_x.dtype)
# Obs.: Como dados_a foi definido como um array de elementos int32, ele
#       permanecerá como um array composto  por elementos int32.  Neste
#       exemplo, na atribuição, NumPy muda 123.77 para 123, porém estás
#       conversões não funcionam para todos os tipos numéricos.

In [ ]:
# Retorna um novo array contendo todos os elementos do array 
# corrente, porém com o tipo alterado.
dados_b = dados_a.astype('float128')
print(dados_b)
print(dados_b.dtype)

In [ ]:
# Retorna um novo array contendo todos os elementos do array 
# corrente, porém com o tipo alterado.
dados_b = dados_a.astype('int32')
print(dados_b)
print(dados_b.dtype)

In [ ]:
# Retorna um novo array contendo todos os elementos do array 
# corrente, porém com o tipo alterado.
dados_b = dados_a.astype('<U8')
print(dados_b)
print(dados_b.dtype)

In [ ]:
# Fim ;-)